### ISSUE TITLE
typo in function testing cell

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-welchs-ttest-lab#3]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [x] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue

The penultimate cell has a typo. It's testing the function we write above it. The third param should say "two_sided", but right now it says "two_side".

### Source

```
p_value(treatment, control, two_side=True)
```

### Concern

It throws an error when you try to run it even if your code works.

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
We are no longer keeping this repo updated since it is not part of v3.0 or beyond.
